src/java/de/parkinglist/entities/Carparkfacility1.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.parkinglist.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author pulkit
 */
@Entity
@Table(name = "carparkfacility1")
@NamedQueries({
    @NamedQuery(name = "Carparkfacility1.findAll", query = "SELECT c FROM Carparkfacility1 c"),
    @NamedQuery(name = "Carparkfacility1.findByCpfacility1id", query = "SELECT c FROM Carparkfacility1 c WHERE c.cpfacility1id = :cpfacility1id"),
    @NamedQuery(name = "Carparkfacility1.findByFacility", query = "SELECT c FROM Carparkfacility1 c WHERE c.facility = :facility"),
    @NamedQuery(name = "Carparkfacility1.findByStatus", query = "SELECT c FROM Carparkfacility1 c WHERE c.status = :status")})
public class Carparkfacility1 implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "cpfacility1id")
    private Integer cpfacility1id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 60)
    @Column(name = "facility")
    private String facility;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 31)
    @Column(name = "status")
    private String status;
    @JoinColumn(name = "parkhausid", referencedColumnName = "parkhausid")
    @ManyToOne(optional = false)
    private Parkhaus parkhausid;

    public Carparkfacility1() {
    }

    public Carparkfacility1(Integer cpfacility1id) {
        this.cpfacility1id = cpfacility1id;
    }

    public Carparkfacility1(Integer cpfacility1id, String facility, String status) {
        this.cpfacility1id = cpfacility1id;
        this.facility = facility;
        this.status = status;
    }

    public Integer getCpfacility1id() {
        return cpfacility1id;
    }

    public void setCpfacility1id(Integer cpfacility1id) {
        this.cpfacility1id = cpfacility1id;
    }

    public String getFacility() {
        return facility;
    }

    public void setFacility(String facility) {
        this.facility = facility;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Parkhaus getParkhausid() {
        return parkhausid;
    }

    public void setParkhausid(Parkhaus parkhausid) {
        this.parkhausid = parkhausid;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (cpfacility1id != null ? cpfacility1id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Carparkfacility1)) {
            return false;
        }
        Carparkfacility1 other = (Carparkfacility1) object;
        if ((this.cpfacility1id == null && other.cpfacility1id != null) || (this.cpfacility1id != null && !this.cpfacility1id.equals(other.cpfacility1id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "de.parkinglist.entities.Carparkfacility1[ cpfacility1id=" + cpfacility1id + " ]";
    }
    
}

src/java/de/parkinglist/jsf/Carparkfacility1Controller.java
package de.parkinglist.jsf;

import de.parkinglist.entities.Carparkfacility1;
import de.parkinglist.jsf.util.JsfUtil;
import de.parkinglist.jsf.util.PaginationHelper;
import de.parkinglist.sessionBeans.Carparkfacility1Facade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "carparkfacility1Controller")
@SessionScoped
public class Carparkfacility1Controller implements Serializable {

    private Carparkfacility1 current;
    private DataModel items = null;
    @EJB
    private de.parkinglist.sessionBeans.Carparkfacility1Facade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public Carparkfacility1Controller() {
    }

    public Carparkfacility1 getSelected() {
        if (current == null) {
            current = new Carparkfacility1();
            selectedItemIndex = -1;
        }
        return current;
    }

    private Carparkfacility1Facade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Carparkfacility1) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Carparkfacility1();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("Carparkfacility1Created"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Carparkfacility1) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("Carparkfacility1Updated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Carparkfacility1) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("Carparkfacility1Deleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Carparkfacility1.class)
    public static class Carparkfacility1ControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            Carparkfacility1Controller controller = (Carparkfacility1Controller) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "carparkfacility1Controller");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Carparkfacility1) {
                Carparkfacility1 o = (Carparkfacility1) object;
                return getStringKey(o.getCpfacility1id());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Carparkfacility1.class.getName());
            }
        }

    }

}

web/pages/carparkfacility1/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateCarparkfacility1Title}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateCarparkfacility1Label_cpfacility1id}" for="cpfacility1id" />
                    <h:inputText id="cpfacility1id" value="#{carparkfacility1Controller.selected.cpfacility1id}" title="#{bundle.CreateCarparkfacility1Title_cpfacility1id}" required="true" requiredMessage="#{bundle.CreateCarparkfacility1RequiredMessage_cpfacility1id}"/>
                    <h:outputLabel value="#{bundle.CreateCarparkfacility1Label_facility}" for="facility" />
                    <h:inputText id="facility" value="#{carparkfacility1Controller.selected.facility}" title="#{bundle.CreateCarparkfacility1Title_facility}" required="true" requiredMessage="#{bundle.CreateCarparkfacility1RequiredMessage_facility}"/>
                    <h:outputLabel value="#{bundle.CreateCarparkfacility1Label_status}" for="status" />
                    <h:inputText id="status" value="#{carparkfacility1Controller.selected.status}" title="#{bundle.CreateCarparkfacility1Title_status}" required="true" requiredMessage="#{bundle.CreateCarparkfacility1RequiredMessage_status}"/>
                    <h:outputLabel value="#{bundle.CreateCarparkfacility1Label_parkhausid}" for="parkhausid" />
                    <h:selectOneMenu id="parkhausid" value="#{carparkfacility1Controller.selected.parkhausid}" title="#{bundle.CreateCarparkfacility1Title_parkhausid}" required="true" requiredMessage="#{bundle.CreateCarparkfacility1RequiredMessage_parkhausid}">
                        <f:selectItems value="#{parkhausController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{carparkfacility1Controller.create}" value="#{bundle.CreateCarparkfacility1SaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{carparkfacility1Controller.prepareList}" value="#{bundle.CreateCarparkfacility1ShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateCarparkfacility1IndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pages/carparkfacility1/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditCarparkfacility1Title}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditCarparkfacility1Label_cpfacility1id}" for="cpfacility1id" />
                    <h:inputText id="cpfacility1id" value="#{carparkfacility1Controller.selected.cpfacility1id}" title="#{bundle.EditCarparkfacility1Title_cpfacility1id}" required="true" requiredMessage="#{bundle.EditCarparkfacility1RequiredMessage_cpfacility1id}"/>
                    <h:outputLabel value="#{bundle.EditCarparkfacility1Label_facility}" for="facility" />
                    <h:inputText id="facility" value="#{carparkfacility1Controller.selected.facility}" title="#{bundle.EditCarparkfacility1Title_facility}" required="true" requiredMessage="#{bundle.EditCarparkfacility1RequiredMessage_facility}"/>
                    <h:outputLabel value="#{bundle.EditCarparkfacility1Label_status}" for="status" />
                    <h:inputText id="status" value="#{carparkfacility1Controller.selected.status}" title="#{bundle.EditCarparkfacility1Title_status}" required="true" requiredMessage="#{bundle.EditCarparkfacility1RequiredMessage_status}"/>
                    <h:outputLabel value="#{bundle.EditCarparkfacility1Label_parkhausid}" for="parkhausid" />
                    <h:selectOneMenu id="parkhausid" value="#{carparkfacility1Controller.selected.parkhausid}" title="#{bundle.EditCarparkfacility1Title_parkhausid}" required="true" requiredMessage="#{bundle.EditCarparkfacility1RequiredMessage_parkhausid}">
                        <f:selectItems value="#{parkhausController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{carparkfacility1Controller.update}" value="#{bundle.EditCarparkfacility1SaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditCarparkfacility1ViewLink}"/>
                <br />
                <h:commandLink action="#{carparkfacility1Controller.prepareList}" value="#{bundle.EditCarparkfacility1ShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditCarparkfacility1IndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pages/carparkfacility1/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListCarparkfacility1Title}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListCarparkfacility1Empty}" rendered="#{carparkfacility1Controller.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{carparkfacility1Controller.items.rowCount > 0}">
                    <h:outputText value="#{carparkfacility1Controller.pagination.pageFirstItem + 1}..#{carparkfacility1Controller.pagination.pageLastItem + 1}/#{carparkfacility1Controller.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{carparkfacility1Controller.previous}" value="#{bundle.Previous} #{carparkfacility1Controller.pagination.pageSize}" rendered="#{carparkfacility1Controller.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{carparkfacility1Controller.next}" value="#{bundle.Next} #{carparkfacility1Controller.pagination.pageSize}" rendered="#{carparkfacility1Controller.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{carparkfacility1Controller.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarparkfacility1Title_cpfacility1id}"/>
                            </f:facet>
                            <h:outputText value="#{item.cpfacility1id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarparkfacility1Title_facility}"/>
                            </f:facet>
                            <h:outputText value="#{item.facility}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarparkfacility1Title_status}"/>
                            </f:facet>
                            <h:outputText value="#{item.status}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarparkfacility1Title_parkhausid}"/>
                            </f:facet>
                            <h:outputText value="#{item.parkhausid}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{carparkfacility1Controller.prepareView}" value="#{bundle.ListCarparkfacility1ViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{carparkfacility1Controller.prepareEdit}" value="#{bundle.ListCarparkfacility1EditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{carparkfacility1Controller.destroy}" value="#{bundle.ListCarparkfacility1DestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{carparkfacility1Controller.prepareCreate}" value="#{bundle.ListCarparkfacility1CreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListCarparkfacility1IndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pages/carparkfacility1/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewCarparkfacility1Title}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewCarparkfacility1Label_cpfacility1id}"/>
                    <h:outputText value="#{carparkfacility1Controller.selected.cpfacility1id}" title="#{bundle.ViewCarparkfacility1Title_cpfacility1id}"/>
                    <h:outputText value="#{bundle.ViewCarparkfacility1Label_facility}"/>
                    <h:outputText value="#{carparkfacility1Controller.selected.facility}" title="#{bundle.ViewCarparkfacility1Title_facility}"/>
                    <h:outputText value="#{bundle.ViewCarparkfacility1Label_status}"/>
                    <h:outputText value="#{carparkfacility1Controller.selected.status}" title="#{bundle.ViewCarparkfacility1Title_status}"/>
                    <h:outputText value="#{bundle.ViewCarparkfacility1Label_parkhausid}"/>
                    <h:outputText value="#{carparkfacility1Controller.selected.parkhausid}" title="#{bundle.ViewCarparkfacility1Title_parkhausid}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{carparkfacility1Controller.destroyAndView}" value="#{bundle.ViewCarparkfacility1DestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewCarparkfacility1EditLink}"/>
                <br />
                <h:commandLink action="#{carparkfacility1Controller.prepareCreate}" value="#{bundle.ViewCarparkfacility1CreateLink}" />
                <br />
                <h:commandLink action="#{carparkfacility1Controller.prepareList}" value="#{bundle.ViewCarparkfacility1ShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewCarparkfacility1IndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>